### ISSUE TITLE
No log files found

### ISSUE THREAD

**Issue by mwoodbri** [ImperialCollegeLondon/rcs_cluster_scripts#1]
```
$ ls
covid-sim.e1500539  covid-sim.o1500539  run_sample.pbs.sh
$ latest_log 
ls: cannot access *.+([0-9])?(.+([0-9])): No such file or directory
No log files found
```

**Comment by mwoodbri** [comment]
RTFM

**Comment by cc-a** [comment]
None the less I've tweaked so the user is prompted with the usage string in this scenario

**Comment by mwoodbri** [comment]
Thanks - great idea. In terms of idiot-proofing: if I was confused then maybe someone might have been too ;)

BTW... this is where a module would help: so that all users immediately get improvements. Or, more importantly, any critical fixes (though I appreciate risks here are relatively low!). I'm not sure I'm going to remember to `git pull` very often...
